const TOTAL_VOLUME_DECIMALS = 36;
const LIQUIDITY_DECIMALS = 9;
const SRG_PRICE_DECIMALS = 27;
const CALCULATE_PRICE_DECIMALS = 18;

export { TOTAL_VOLUME_DECIMALS, LIQUIDITY_DECIMALS, SRG_PRICE_DECIMALS, CALCULATE_PRICE_DECIMALS };
